<?xml version="1.0"?>
<!DOCTYPE CASES [
<!ELEMENT CASES (CRASH+)>
<!ELEMENT CRASH (TIME,INVOLVED_PERSONS,SEVERERITY,CRASH_LOCATION, EMERGENCY_CENTRE, MANAGING_DOCTOR, EMERGENCY_ROOM_USED)>
<!ELEMENT TIME (DATE, HOUR)>
<!ELEMENT DATE (#PCDATA)>
<!ELEMENT HOUR (#PCDATA)>
<!ELEMENT INVOLVED_PERSONS (#PCDATA)>
<!ELEMENT VEHICLE (VEHICLE_TYPE, NUMBER_PLATE)>
<!ELEMENT VEHICLE_TYPE (#PCDATA)>
<!ELEMENT NUMBER_PLATE (#PCDATA)>
<!ELEMENT SEVERERITY (#PCDATA)>
<!ELEMENT CRASH_LOCATION (#PCDATA)>
<!ELEMENT EMERGENCY_CENTRE (CENTRE_NAME, CENTRE_LOCATION)>
<!ELEMENT CENTRE_NAME (#PCDATA)>
<!ELEMENT CENTRE_LOCATION (#PCDATA)>
<!ELEMENT MANAGING_DOCTOR (DOC_NAME, DOC_EMAIL)>
<!ELEMENT DOC_NAME (#PCDATA)>
<!ELEMENT DOC_EMAIL (#PCDATA)>
<!ELEMENT EMERGENCY_ROOM_USED (#PCDATA)>
]>

<CASES>
<CRASH>
<TIME>
<DATE>01/07/2020</DATE>
<HOUR>1700HRS</HOUR>
</TIME>
<VEHICLE>
<VEHICLE_TYPE>Car</VEHICLE_TYPE>
<NUMBER_PLATE>RAC102B</NUMBER_PLATE>
</VEHICLE>
<INVOLVED_PERSONS>6</INVOLVED_PERSONS>
<SEVERERITY>Red</SEVERERITY>
<LOCATION>Gikondo</LOCATION>
<EMERGENCY_CENTRE>
<CENTRE_NAME>Gikondo Medical Centre</CENTRE_NAME>
<CENTRE_LOCATION>Gikondo Medical Centre</CENTRE_LOCATION>
</EMERGENCY_CENTRE>

<EMERGENCY_ROOM_USED>RM1</EMERGENCY_ROOM_USED>
<MANAGING_DOCTOR>
<DOC_NAME>DR. Bukeko Charles</DOC_NAME>
<DOC_EMAIL>bukeko@gmail.com </DOC_EMAIL>
</MANAGING_DOCTOR>
</CRASH>

<CRASH>
<TIME>
<DATE>01/07/2020</DATE>
<HOUR>1400HRS</HOUR>
</TIME>
<VEHICLE>
<VEHICLE_TYPE>Lorry</VEHICLE_TYPE>
<NUMBER_PLATE>RAJ190Q</NUMBER_PLATE>
</VEHICLE>
<INVOLVED_PERSONS>10</INVOLVED_PERSONS>
<SEVERERITY>Yellow</SEVERERITY>
<LOCATION>Gikondo</LOCATION>
<EMERGENCY_CENTRE>
<CENTRE_NAME>Gikondo Medical Centre</CENTRE_NAME>
<CENTRE_LOCATION>Gikondo Medical Centre</CENTRE_LOCATION>
</EMERGENCY_CENTRE>

<EMERGENCY_ROOM_USED>RM1</EMERGENCY_ROOM_USED>
<MANAGING_DOCTOR>
<DOC_NAME>DR. Bukeko Charles</DOC_NAME>
<DOC_EMAIL>bukeko@gmail.com </DOC_EMAIL>
</MANAGING_DOCTOR>
</CRASH>

<CRASH>
<TIME>
<DATE>01/07/2020</DATE>
<HOUR>1700HRS</HOUR>
</TIME>
<VEHICLE>
<VEHICLE_TYPE>Bus</VEHICLE_TYPE>
<NUMBER_PLATE>RAP110E</NUMBER_PLATE>
</VEHICLE>
<INVOLVED_PERSONS>18</INVOLVED_PERSONS>
<SEVERERITY>Green</SEVERERITY>
<LOCATION>Gikondo</LOCATION>
<EMERGENCY_CENTRE>
<CENTRE_NAME>Gikondo Medical Centre</CENTRE_NAME>
<CENTRE_LOCATION>Gikondo Medical Centre</CENTRE_LOCATION>
</EMERGENCY_CENTRE>

<EMERGENCY_ROOM_USED>RM1</EMERGENCY_ROOM_USED>
<MANAGING_DOCTOR>
<DOC_NAME>DR. Bukeko Charles</DOC_NAME>
<DOC_EMAIL>bukeko@gmail.com </DOC_EMAIL>
</MANAGING_DOCTOR>
</CRASH>

<CRASH>
<TIME>
<DATE>02/07/2020</DATE>
<HOUR>1500HRS</HOUR>
</TIME>
<VEHICLE>
<VEHICLE_TYPE>Lorry</VEHICLE_TYPE>
<NUMBER_PLATE>RAB100C</NUMBER_PLATE>
</VEHICLE>
<INVOLVED_PERSONS>2</INVOLVED_PERSONS>
<SEVERERITY>Green</SEVERERITY>
<CRASH_LOCATION>Nyambungogo</CRASH_LOCATION>
<EMERGENCY_CENTRE>
<CENTRE_NAME>Nyambungogo Medical Centre</CENTRE_NAME>
<CENTRE_LOCATION>Nyambungogo</CENTRE_LOCATION>
</EMERGENCY_CENTRE>
<EMERGENCY_ROOM_USED>RM3</EMERGENCY_ROOM_USED>
<MANAGING_DOCTOR>
<DOC_NAME>DR. Melanie </DOC_NAME>
<DOC_EMAIL>melanie@gmail.com</DOC_EMAIL>
</MANAGING_DOCTOR>
</CRASH>

<CRASH>
<TIME>
<DATE>03/07/2020</DATE>
<HOUR>1200HRS</HOUR>
</TIME>
<VEHICLE>
<VEHICLE_TYPE>Cab</VEHICLE_TYPE>
<NUMBER_PLATE>Yellow</NUMBER_PLATE>
</VEHICLE>
<INVOLVED_PERSONS>5</INVOLVED_PERSONS>
<SEVERERITY>Green</SEVERERITY>
<CRASH_LOCATION>Kichichuro</CRASH_LOCATION>
<EMERGENCY_CENTRE>
<CENTRE_NAME>Kichichuro Medical Centre</CENTRE_NAME>
<CENTRE_LOCATION>Nyambungogo</CENTRE_LOCATION>
</EMERGENCY_CENTRE>
<EMERGENCY_ROOM_USED>RM5</EMERGENCY_ROOM_USED>
<MANAGING_DOCTOR>
<DOC_NAME>DR. Hussein </DOC_NAME>
<DOC_EMAIL>hussein@gmail.com</DOC_EMAIL>
</MANAGING_DOCTOR>
</CRASH>

<CRASH>
<TIME>
<DATE>04/07/2020</DATE>
<HOUR>1300HRS</HOUR>
</TIME>
<VEHICLE>
<VEHICLE_TYPE>Motorcycle</VEHICLE_TYPE>
<NUMBER_PLATE>RAD101C</NUMBER_PLATE>
</VEHICLE>
<INVOLVED_PERSONS>3</INVOLVED_PERSONS>
<SEVERERITY>Red</SEVERERITY>
<CRASH_LOCATION>Mumuji</CRASH_LOCATION>
<EMERGENCY_CENTRE>
<CENTRE_NAME>City Medical Centre</CENTRE_NAME>
<CENTRE_LOCATION>City Centre</CENTRE_LOCATION>
</EMERGENCY_CENTRE>
<EMERGENCY_ROOM_USED>RM15</EMERGENCY_ROOM_USED>
<MANAGING_DOCTOR>
<DOC_NAME>DR. Eliza </DOC_NAME>
<DOC_EMAIL>eliza@gmail.com</DOC_EMAIL>
</MANAGING_DOCTOR>
</CRASH>

<CRASH>
<TIME>
<DATE>05/07/2020</DATE>
<HOUR>1800HRS</HOUR>
</TIME>
<VEHICLE>
<VEHICLE_TYPE>Bus</VEHICLE_TYPE>
<NUMBER_PLATE>RAK400C</NUMBER_PLATE>
</VEHICLE>
<INVOLVED_PERSONS>10</INVOLVED_PERSONS>
<SEVERERITY>Red</SEVERERITY>
<CRASH_LOCATION>Nyamirambo</CRASH_LOCATION>
<EMERGENCY_CENTRE>
<CENTRE_NAME>Nyamirambo Medical Centre</CENTRE_NAME>
<CENTRE_LOCATION>Nyamirambo</CENTRE_LOCATION>
</EMERGENCY_CENTRE>
<EMERGENCY_ROOM_USED>RM2</EMERGENCY_ROOM_USED>
<MANAGING_DOCTOR>
<DOC_NAME>DR. Guyo Jarso </DOC_NAME>
<DOC_EMAIL>guyo@gmail.com</DOC_EMAIL>
</MANAGING_DOCTOR>
</CRASH>

<CRASH>
<TIME>
<DATE>06/07/2020</DATE>
<HOUR>1700HRS</HOUR>
</TIME>
<VEHICLE>
<VEHICLE_TYPE>Van</VEHICLE_TYPE>
<NUMBER_PLATE>RAF301E</NUMBER_PLATE>
</VEHICLE>
<INVOLVED_PERSONS>20</INVOLVED_PERSONS>
<SEVERERITY>Yellow</SEVERERITY>
<CRASH_LOCATION>Nyarugenge</CRASH_LOCATION>
<EMERGENCY_CENTRE>
<CENTRE_NAME>Nyarugenge Medical Centre</CENTRE_NAME>
<CENTRE_LOCATION>Nyarugenge</CENTRE_LOCATION>
</EMERGENCY_CENTRE>
<EMERGENCY_ROOM_USED>RM16</EMERGENCY_ROOM_USED>
<MANAGING_DOCTOR>
<DOC_NAME>DR. Eric Kabaye</DOC_NAME>
<DOC_EMAIL>kabaye@gmail.com</DOC_EMAIL>
</MANAGING_DOCTOR>
</CRASH>

<CRASH>
<TIME>
<DATE>07/07/2020</DATE>
<HOUR>2100HRS</HOUR>
</TIME>
<VEHICLE>
<VEHICLE_TYPE>Car</VEHICLE_TYPE>
<NUMBER_PLATE>RAD400E</NUMBER_PLATE>
</VEHICLE>
<INVOLVED_PERSONS>6</INVOLVED_PERSONS>
<SEVERERITY>Red</SEVERERITY>
<CRASH_LOCATION>Kicukiro</CRASH_LOCATION>
<EMERGENCY_CENTRE>
<CENTRE_NAME>Kicukiro Medical Centre</CENTRE_NAME>
<CENTRE_LOCATION>Nyarugenge</CENTRE_LOCATION>
</EMERGENCY_CENTRE>
<EMERGENCY_ROOM_USED>RM9</EMERGENCY_ROOM_USED>
<MANAGING_DOCTOR>
<DOC_NAME>DR. Bonny Khalwale</DOC_NAME>
<DOC_EMAIL>bonnie@gmail.com</DOC_EMAIL>
</MANAGING_DOCTOR>
</CRASH>
</CASES >




(:for $t in //CRASH
return <crash>{($t/TIME, $t/SEVERERITY, $t/INVOLVED_PERSONS, $t/CRASH_LOCATION)}</crash>:)


(:let $sequence := (//EMERGENCY_ROOM_USED)

for $maxFreq in 
           max(for $val in distinct-values($sequence)
                     return count(index-of($sequence, $val))
               )
   return
      distinct-values($sequence)[count(index-of($sequence, .)) eq $maxFreq]:)



(:<crash>
  <TIME>
    <DATE>01/07/2020</DATE>
    <HOUR>1700HRS</HOUR>
  </TIME>
  <SEVERERITY>Red</SEVERERITY>
  <INVOLVED_PERSONS>6</INVOLVED_PERSONS>
</crash>
<crash>
  <TIME>
    <DATE>01/07/2020</DATE>
    <HOUR>1400HRS</HOUR>
  </TIME>
  <SEVERERITY>Yellow</SEVERERITY>
  <INVOLVED_PERSONS>10</INVOLVED_PERSONS>
</crash>
<crash>
  <TIME>
    <DATE>01/07/2020</DATE>
    <HOUR>1700HRS</HOUR>
  </TIME>
  <SEVERERITY>Green</SEVERERITY>
  <INVOLVED_PERSONS>18</INVOLVED_PERSONS>
</crash>
<crash>
  <TIME>
    <DATE>02/07/2020</DATE>
    <HOUR>1500HRS</HOUR>
  </TIME>
  <SEVERERITY>Green</SEVERERITY>
  <INVOLVED_PERSONS>2</INVOLVED_PERSONS>
  <CRASH_LOCATION>Nyambungogo</CRASH_LOCATION>
</crash>
<crash>
  <TIME>
    <DATE>03/07/2020</DATE>
    <HOUR>1200HRS</HOUR>
  </TIME>
  <SEVERERITY>Green</SEVERERITY>
  <INVOLVED_PERSONS>5</INVOLVED_PERSONS>
  <CRASH_LOCATION>Kichichuro</CRASH_LOCATION>
</crash>
<crash>
  <TIME>
    <DATE>04/07/2020</DATE>
    <HOUR>1300HRS</HOUR>
  </TIME>
  <SEVERERITY>Red</SEVERERITY>
  <INVOLVED_PERSONS>3</INVOLVED_PERSONS>
  <CRASH_LOCATION>Mumuji</CRASH_LOCATION>
</crash>
<crash>
  <TIME>
    <DATE>05/07/2020</DATE>
    <HOUR>1800HRS</HOUR>
  </TIME>
  <SEVERERITY>Red</SEVERERITY>
  <INVOLVED_PERSONS>10</INVOLVED_PERSONS>
  <CRASH_LOCATION>Nyamirambo</CRASH_LOCATION>
</crash>
<crash>
  <TIME>
    <DATE>06/07/2020</DATE>
    <HOUR>1700HRS</HOUR>
  </TIME>
  <SEVERERITY>Yellow</SEVERERITY>
  <INVOLVED_PERSONS>20</INVOLVED_PERSONS>
  <CRASH_LOCATION>Nyarugenge</CRASH_LOCATION>
</crash>
<crash>
  <TIME>
    <DATE>07/07/2020</DATE>
    <HOUR>2100HRS</HOUR>
  </TIME>
  <SEVERERITY>Red</SEVERERITY>
  <INVOLVED_PERSONS>6</INVOLVED_PERSONS>
  <CRASH_LOCATION>Kicukiro</CRASH_LOCATION>
</crash>:)


(:let $sequence := (//EMERGENCY_ROOM_USED)

for $maxFreq in 
           max(for $val in distinct-values($sequence)
                     return count(index-of($sequence, $val))
               )
   return
      distinct-values($sequence)[count(index-of($sequence, .)) eq $maxFreq]:)





(:RM1:)


      